### ISSUE TITLE
Notify only with OK button vs Confirm forcing 2 options

### ISSUE THREAD

**Issue by SeoRoman** [f3oall/awesome-notifications#17]
**Is your feature request related to a problem? Please describe.**
Ability to remove Cancel button for Confirmation so that it works more like an "Alert Notification" vs a Confirm

IE: Confirm = 2 Actions (OK, CANCEL) 
Notification = 1 Action (OK)

Confirm can be used in both instances, with an option to remove the button cancel

OR...

Replicate AWN.confirm() to AWN.notify() with only a single button action for OK

**Describe the solution you'd like**
Ability to remove the cancel button in a confirm dialog

**Describe alternatives you've considered**
Other packages like sweetalert have the ability to display the dialog but only offer the single option of OK (but I like VueAWN more)

**Additional context**
Don't think I need any

**Comment by f3oall** [comment]
It's reasonable, I will try to implement requested feature during the week

**Comment by f3oall** [comment]
Feature was implemented in 3.0.3. Read docs about confirmation window to learn how to use it.
