### ISSUE TITLE
Problem with Axios and http 400

### ISSUE THREAD

**Issue by paulm17** [f3oall/awesome-notifications#22]
Really like this toaster.  Was using Snotify initially, but this one is much more simplier to use.

Unfortunately, I'm having an issue when returning a 400 request.

    let promise = axios.post("/api/content-editor/visual-builder/save", data);
    let options = {
        labels: {
            async: "Processing"
        }
    };

    let notifier = new AWN(options);
    notifier.async(
        promise,
        resp => {
            if (!this.templateId) {
                this.templateId = resp.data.id;
                this.reSaveStorage(resp.data.id);
            }

            notifier.success(resp.text);
        },
        err => notifier.alert(err.data.text),
        this.notificationText
    );

200 works just fine and a normal axios request such as:

    axios.post("/api/content-editor/visual-builder/save", data)
    .then(response => {
        console.log(response)
    })
    .catch(error => {
        console.log(error.response)
    });

also works just fine, the catch triggers and consoles out the error.

But the with the notification component, axios complains when I'm testing out a failure:

    Uncaught (in promise) Error: Request failed with status code 400
        at createError (app.js:780)
        at settle (app.js:1026)
        at XMLHttpRequest.handleLoad (app.js:293)

    visual-builder.js:22000 Uncaught (in promise) TypeError: Cannot read property 'text' of undefined
        at visual-builder.js:22000
        at vendors~visual-builder.js:10

Thanks

**Comment by Nickfrm** [comment]
The first uncaught promise error was fixed in v3.0.5.
The second error is yours, looks like you trying to get access to non existent property. I think you need to make a check for properties existence before trying to put it into notifier call.
