### ISSUE TITLE
Unable to change icon size for toast using SASS

### ISSUE THREAD

**Issue by Archeelux** [f3oall/awesome-notifications#24]
**Describe the bug**
I am unable to change the icon size, seems like it has a !important property set to 44px and I cannot reduce its size using the $awn-toast-icon-size:

**To Reproduce**
1. Change SASS variable $awn-toast-icon-size: to preferred size
2. Let SASS build

**Expected behavior**
Toast icon should have changed size

**Screenshots**
![image](https://user-images.githubusercontent.com/47854865/64781964-05a64100-d55c-11e9-9e47-c2f0d23b16e6.png)
![image](https://user-images.githubusercontent.com/47854865/64781983-11920300-d55c-11e9-84f6-acf796a16058.png)
![image](https://user-images.githubusercontent.com/47854865/64782017-25d60000-d55c-11e9-80df-b36e97fb0951.png)

Am I doing something wrong maybe?

Thanks

**Comment by Nickfrm** [comment]
I reproduced this steps and all work fine for me. 
![image](https://user-images.githubusercontent.com/35500726/69827746-c9fd4800-1229-11ea-875e-145c9ba9f0af.png)

Also, I see that the style you trying to set (font-size) was applied to ".awn-toast-icon" itself for some reason. It should be set to an icon. (See the screenshot below)
![image](https://user-images.githubusercontent.com/35500726/69827776-ed27f780-1229-11ea-82c4-ed28de9642eb.png)
