### ISSUE TITLE
raw library for CDN 

### ISSUE THREAD

**Issue by poseidonrage** [f3oall/awesome-notifications#25]
I dont think this is an issue, but as i am working on a legacy asp.net web application and had to implement the front end stuff, so i was wondering if i can use this as a standalone file which i can place in script folder and embed it to use,
i mean the project i am working dont support npm

https://f3oall.github.io/dist/index.var.js
https://f3oall.github.io/dist/style.css

These are giving 404 error

Thank You

**Comment by Nickfrm** [comment]
Links for the raw files were fixed in documentation: 
https://f3oall.github.io/awesome-notifications/docs/
