### ISSUE TITLE
Comma between buttons on confirmation popup

### ISSUE THREAD

**Issue by SpaceCudet** [f3oall/awesome-notifications#26]
The confirmation popup displays a comma between the Ok and Cancel buttons - this can be seen in the example in the documentation.

1. Go to Popups: Confirmation documentation
2. Click on first 'Run Example" button
3. See comma between the Ok and Cancel buttons

![image](https://user-images.githubusercontent.com/55992191/65894530-d8ea8a00-e3a1-11e9-8468-a1f5dd1fcc85.png)

 - OS: Windows 10
 - Browser: Chrome, Edge

Looking at the code in popup.js, the buttons are created in an array which is appended to a string using array.join(). The default delimiter for join is a comma, so the solution may be to use a parameter of an empty string: buttons.join('').

**Comment by Nickfrm** [comment]
Fixed in v3.0.4
Thanks for your feedback

**Comment by soubhikchatterjee** [comment]
This is back in v3.0.6

Kindly fix.
