### ISSUE TITLE
Keyboard navigation

### ISSUE THREAD

**Issue by iGadget73** [f3oall/awesome-notifications#27]
In my app the awn confirm pops up pretty often and I miss the opportunity to press return or hit esc to navigate through it. 

A simple keyboard binding would be awesomenazing and helpful for the best UX.
The green (confirm-ok) button should be automatically bound to the return key and the red (confirm-cancel) to the esc key.

Also options to change that default behaviour would be awesome!

**Comment by Nickfrm** [comment]
Hi! Buttons behavior is same as you described (for Esc or Enter key) and works fine for me. Can you specify version of library you use? Probably you're using old one.

**Comment by iGadget73** [comment]
Yeah, the update made it work again.
