### ISSUE TITLE
Strange documentation about modal labels (ok / cancel)

### ISSUE THREAD

**Issue by gaetanhauray** [f3oall/awesome-notifications#37]
The documentation about the buttons labels of modal seem to not be updated to the last version : 3.0.3.
Here the documentation [confirmok](https://f3oall.github.io/awesome-notifications/docs/customization/labels#confirmok) & [confirmcancel](https://f3oall.github.io/awesome-notifications/docs/customization/labels#confirmcancel)

**What the documentation say :**
The documentation say to use the following options to change label :
`options.modal = {
  cancelLabel: "Annuler",
  ...
}`

**What I had to do :**
In fact I had to use the following options to made it :
`options.labels = {
  confirmCancel: "Annuler",
  ...
}`

**How I find it :**
I find the good option by looking at the code of popup.js :
`<button [...]>${this.options.labels.confirmOk}</button>`
`<button [...]>${this.options.labels.confirmCancel}</button>`

Despite that, I really enjoyed use this lib and the documentation is well done ! 
Thank you

**Comment by Nickfrm** [comment]
Thanks for your participation. Documentation was updated. This was obsolete docs for 2.x.x version. If you're was migrating from 2 to 3 version, please check updates: https://f3oall.github.io/awesome-notifications/docs/migrations/from-2-to-3
