### ISSUE TITLE
Different duration for different notifications

### ISSUE THREAD

**Issue by n-osennij** [f3oall/awesome-notifications#4]
How can I set 2000ms duration for success notification and no auto close for warning notification? I realy need to auto hide success notifications and do not auto hide warning notifications.

**Comment by f3oall** [comment]
For now you can't do that. I will add this feature in next update.

Thanks for your feedback.

**Comment by capuderg** [comment]
The "non-auto-close" feature would be awesome for warnings and errors. 

Just wanted to add +1 for this feature request.

**Comment by f3oall** [comment]
Implemented in version 3.0.0
