### ISSUE TITLE
Prevent from closeing with Esc

### ISSUE THREAD

**Issue by hadi4172** [f3oall/awesome-notifications#40]
**Is your feature request related to a problem? Please describe.**
I need to force the user to do something on the confirm popup, however this can't happen if the user close it with the esc button

**Describe the solution you'd like**
Can you add an option to prevent the modal from closing on esc button keypress ?

**Describe alternatives you've considered**
I tried to remove all the keypress keylisteners but its very not optimal.

Thank you

**Comment by hadi4172** [comment]
I finally just had to delete some chars in the code of the library so it's fine.

**Comment by manchumahara** [comment]
Anyway to prevent closing clicking outside and display a close button in modal ?
