### ISSUE TITLE
Please add `dist/index.var.js` in the package shipped with in npm

### ISSUE THREAD

**Issue by wucke13** [f3oall/awesome-notifications#5]
Running
`npm install --save awesome-notifications && ls node_modules/awesome-notifications/dist` returns
`index.js  style.css` - so `index.var.js` is missing.

I would love to use npm to pull this dependecy, therefore my appeal is: please include it.

Thanks!

**Comment by f3oall** [comment]
Hi,

It makes sense, i will add `index.var.js` in near update.

Thanks for your interest!

**Comment by wucke13** [comment]
Perfect, thanks!

**Comment by wucke13** [comment]
four months passed, the current release in npm does still not contain `index.var.js`, rendering awesome-notifications npm package useless for client side delivery. Please fix this ASAP!

**Comment by f3oall** [comment]
Implemented in version 3.0.0
