### ISSUE TITLE
DEPRECATION WARNING: $saturation: Passing a number without unit % (0) is deprecated.

### ISSUE THREAD

**Issue by dmitryuk** [f3oall/awesome-notifications#52]
Webpack 5 throws an error 
`DEPRECATION WARNING: $saturation: Passing a number without unit % (0) is deprecated.`

Latest version  3.1.2 still contains the error.
Please reopen and accept my PR https://github.com/f3oall/awesome-notifications/pull/48
Thank you

**Comment by Ph0tonic** [comment]
Hello,
Any update on this ?
This warning appears only for 3 lines with a specific `0` value.
Thank you very much for your work @f3oall

**Comment by phoenixr3** [comment]
Should be fixed in 3.1.3

**Comment by Ph0tonic** [comment]
Fixed with latest version 3.1.3 :+1: 
Can be closed
