### ISSUE TITLE
confirm/modal title text

### ISSUE THREAD

**Issue by n-osennij** [f3oall/awesome-notifications#8]
Hi! There are no option to change `confirm` title message - CONFIRMATION REQUIRED. Now `modal` have only 3 options: `modal.okLabel`, `modal.cancelLabel`, `modal.maxWidth`. Is is possible to add option `modal.title`?

**Comment by f3oall** [comment]
It's possible via options override in version 3.0.0
```
let options = {labels: {confirm: "Confirm label override"}}
this.confirm("Your custom html", onOk, onCancel, options )
```
