### ISSUE TITLE
[Suggestion] Override options for each call

### ISSUE THREAD

**Issue by pdcmoreira** [f3oall/awesome-notifications#9]
My suggestion is that, for each individual call, an options object could be passed, overriding the initialization ones.
Something like:
```javascript
this.$awn.tip('Hello world!', options)
```

Or, at least, we should be able to pass the title (for translation purposes), like:
```javascript
this.$awn.success('Hello world!', 'Sucesso')
```

**Comment by f3oall** [comment]
Entire options override per call will be implemented in version 3.0.0
